"""Created Banner Image table

Revision ID: 4a2ab03cbc16
Revises: 6e87340db92c
Create Date: 2024-02-03 15:24:48.817245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2ab03cbc16'
down_revision = '6e87340db92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Banner Image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Banner Image')
    # ### end Alembic commands ###
