"""empty message

Revision ID: 6f1bfebcb308
Revises: 3fae54be3966
Create Date: 2024-02-20 16:33:11.459497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1bfebcb308'
down_revision = '3fae54be3966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
