"""Reconfigure the models

Revision ID: bba16be2840d
Revises: 4a2ab03cbc16
Create Date: 2024-02-06 19:20:02.356517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba16be2840d'
down_revision = '4a2ab03cbc16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paragraph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_image', sa.String(length=255), nullable=True),
    sa.Column('paragraph_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraph.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('epigraph', sa.Text(), nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('epigraph')
        batch_op.drop_column('main_image')

    op.drop_table('image')
    op.drop_table('paragraph')
    # ### end Alembic commands ###
