"""Added paragraph number column

Revision ID: c2332f4d3979
Revises: 
Create Date: 2024-02-21 09:26:59.944668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2332f4d3979'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Banner Image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('main_image', sa.String(length=255), nullable=True),
    sa.Column('epigraph', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paragraph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('para_number', sa.Integer(), nullable=False),
    sa.Column('fk_paragraph_to_articles', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_paragraph_to_articles'], ['article.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_content_image_to_articles', sa.String(length=255), nullable=True),
    sa.Column('fk_image_paragraph', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_content_image_to_articles'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fk_image_paragraph'], ['paragraph.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('paragraph')
    op.drop_table('article')
    op.drop_table('Banner Image')
    # ### end Alembic commands ###
